language: java
jdk:
  - oraclejdk8
  - oraclejdk9
sudo: false
before_install:
  - chmod +x ./gradlew
script:
  - ./gradlew check
  - ./gradlew javadoc
  - ./gradlew jacocoTestReport
deploy:
  provider: script
  skip_cleanup: true
  script: ./gradlew bintrayUpload -Ddeployment=true
  on:
    tags: true
    jdk: oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
